### PR TITLE
fix issue 559

### PR DESCRIPTION
**Pull request by enniel**
This PR fixed issue #559

### CODE REVIEW

**Comment by srt0422** [comment]
please merge soon.  This issue is breaking my project

**Comment by ShvedDmutro** [comment]
I have same issue

**Comment by Samueljoli** [comment]
me three

**Comment by quangrau** [comment]
Still get this error. I was tried 3 recently versions but didn't work.

```   
     "native-base": "^2.1.3",
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.3",
```

**Pull request closed without merging**
