### PR TITLE
Updated extended prop names

### PR DESCRIPTION
**Pull request by darkmantle**
The types have changed for react-native causing compiler errors when using TypeScript.

This is a quick change to fix that.

### CODE REVIEW

**Comment by SupriyaKalghatgi** [comment]
@darkmantle This commit has conflict
why `mode` is missing for Picker?
image

**Comment by darkmantle** [comment]
That is strange...

Will fix that now

**Comment by darkmantle** [comment]
Fixed up to master

**Comment by SupriyaKalghatgi** [comment]
Please exclude `dist` and `__tests__` folder, i.e., dont transpile
commit only the file where you have made changes

**Comment by SupriyaKalghatgi** [comment]
@darkmantle I still find `351` files changed

**Pull request closed without merging**
