### PR TITLE
Small optimizations

### PR DESCRIPTION
**Pull request by cristianoccazinsp**
Replace some of the mostly used components with PureComponent, add some code tweaks to reduce the component's overhead, and use RN's style merger instead of manually reducing the list.

Please review! I've tested it on a Moto G5 and although the improvements are minimal when the components are re-rendered due to props change or mount, it can be noticeable on re-renders.

Wish some of the styled buttons overhead could be reduced even further.

### CODE REVIEW

**Comment by cristianoccazinsp** [comment]
Any review/news on this? Can definitely use the extra performance boost on my project but right now I have to monkey patch from node_modules until this is merged and release.
Can someone review?

**Comment by cristianoccazinsp** [comment]
Could really use this getting merged so I can install from npm instead of my own repo + manual building. Been running apps with this change and haven't found issues so far.

**Comment by cristianoccazinsp** [comment]
Committed a small change that I overlooked when simplifying some code. It was only visible when using Android ripple since the code below uses the flattened version of styles.

**Comment by cristianoccazinsp** [comment]
Any updates? Starting to get behind master. Should I pull master changes into the branch and create a new commit?

**Comment by cristianoccazinsp** [comment]
Hey guys, any updates? The library seems abandoned right now, are you guys still maintaining it?

**Review by hanykumar — APPROVED** [review]
This PR works fine. Found no issue with Button, Icon and Text.

**Review by shivrajkumar — APPROVED** [review]

**Pull request merged**
