### PR TITLE
Picker has been extracted from react-native core

### PR DESCRIPTION
**Pull request by Preeternal**
The [issue](https://github.com/GeekyAnts/NativeBase/issues/3114)
Could you please to review?

### CODE REVIEW

**Comment by Preeternal** [comment]
replaced community-picker into peerDependencies

**Comment by lifenautjoe** [comment]
Can someone please merge and release this? Blocking as it prevents app instantiation with 
```
 Invariant Violation: Tried to register two views with the same name AndroidDropdownPicker
```

**Comment by alexandrtovmach** [comment]
@Preeternal I'm not sure that's moving required dependency to `peerDependencies` is good idea

#3230 it's duplicate, but it used "normal" `dependencies`, so my vote for that

**Comment by Preeternal** [comment]
> @Preeternal I'm not sure that's moving required dependency to `peerDependencies` is good idea
> 
> #3230 it's duplicate, but it used "normal" `dependencies`, so my vote for that
But someone probably will want to use community picker and native-base in own project same time. It will return error described by @lifenautjoe

**Pull request closed without merging**
