### PR TITLE
Fix floatingLabel animation

### PR DESCRIPTION
**Pull request by elyalvarado**
This is commit fixes the expected animation for the floating label,
which should change the fontSize and line height when the field is
focused.

This is basically reverting commit [3e3ba4e](https://github.com/GeekyAnts/NativeBase/commit/3e3ba4e1a273da9b3236e0f6696e3873152d4a8f#diff-f1939c40e767531823521e714e4db9c0), which was theoretically fixing #2248, but the true is that the root cause of that issue was not in that line, and instead it caused a regression were the floatingLabel is not resizing to an smaller size on focusing the input.

The current behaviour without this fix is:

current

The expected behaviour is (making the label smaller when focusing):

expected

With this fix you're still able to change the color of the label by applying style directly to it (which I understand was what initially was reported as an issue in #2248):

expectedcolor

### CODE REVIEW

**Comment by elyalvarado** [comment]
@SupriyaKalghatgi can you take a look at this? Is a trivial fix and it affects the UX for people that upgraded to v2.8.1

**Comment by elyalvarado** [comment]
@Angelk90 there are two ways that should work, but the behavior will depend on the version of native-base you are using:
1. Add the color style directly to your `Label` in this way: `<Label style={{color: 'blue'}}>`.
  1.1 If you're using 2.8.1 this will change the label color for both floating/not floating, but the font-size won't decrease when floating.
  1.2 If you're using 2.8.0 this will change the label color for not floating, but not when floating
  1.3 If this commit is merged it'll behave as expected
2. Eject the theme and change the `inputColorPlaceholder` property.
  2.1 If you're using 2.8.1 it'll behave the same as point 1.1 above
  2.2 If you're using 2.8.0 it'll behave as expected
  2.3 If this commit is merged it'll behave as expected

**Comment by elyalvarado** [comment]
@SupriyaKalghatgi I amended the commit, and it now fixes #2248 and removes the regression for not changing the label font size when floating. The root cause of the issue was that StyleSheet.flatten should have been called with an array, otherwise it just returns the first argument and therefore was disregarding the actual Label styles coming from the props.

**Comment by Angelk90** [comment]
@elyalvarado : The button in the input field for the clear? Can you post an example, for example on snack.expo.io?

**Comment by elyalvarado** [comment]
@Angelk90, I see what you mean now. 

The button clearing the fields that you see at the right end of it in my gifs is the native iOS clear button, which I enabled by passing ` clearButtonMode: 'while-editing'`  as prop to the `Input`, which in turns passes it to the underlying react-native `TextInput` component (see [React Native Documentation](https://facebook.github.io/react-native/docs/textinput#clearbuttonmode).

Unfortunately, that property is iOS specific, and you can't style it.

**Comment by SupriyaKalghatgi** [comment]
@elyalvarado I will take a look on this

**Comment by iamsokol** [comment]
@elyalvarado @SupriyaKalghatgi
Why doesn`t label  font size decrease on input focus? What can I do with it?
"native-base": "2.10.0",
"react-native": "0.57.7",

exemple

**Comment by elyalvarado** [comment]
@iamsokol even though the PR was already merged, it was merged before the release of the 2.10.0 version of `native-base`. It'll be sure included in the next version release.

**Comment by iamsokol** [comment]
@elyalvarado As I understand it is already released (as I saw versions fix),but it doesn't work in my code.

**Comment by elyalvarado** [comment]
Is merged, but not yet released, take a look at the list of [commits](https://github.com/GeekyAnts/NativeBase/commits/master) and you'll see that the merge commit is just after the one tagged 2.10.0

**Comment by iamsokol** [comment]
2.8.2
> Item: FloatingLabel animation issue fixed.

@elyalvarado What is this fix about!Can it help me?

**Comment by elyalvarado** [comment]
@iamsokol that fixed another issue with the floating label color, but introduced the size issue.

**Comment by iamsokol** [comment]
@elyalvarado can I change label color, when input has focus?

**Pull request merged**
