### PR TITLE
fix: react-native-keyboard-aware-scroll-view from 1.0.0 to 1.0.1

### PR DESCRIPTION
**Pull request by hanykumar**
#3243

### CODE REVIEW

**Comment by seavan** [comment]
please merge!

**Comment by summerkiflain** [comment]
Please please merge this, and npm publish soon.

**Comment by kkokey** [comment]
Please merge!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by cecil-chen** [comment]
Does this change get merged?

**Comment by mattrabe** [comment]
@cecil-chen It looks like this PR was closed without being merged, but a different commit (cd78c88b) with the same change was pushed to master, and was included in the [v2.15.0](https://www.npmjs.com/package/native-base/v/2.15.0) release.

**Pull request closed without merging**
