### PR TITLE
feat: Replaced deprecated DatePicker with @react-native-community solution

### PR DESCRIPTION
**Pull request by alexandrtovmach**
>DatePickerAndroid has been merged with DatePickerIOS and TimePickerAndroid into a single component called DateTimePicker and will be removed in a future release.

https://reactnative.dev/docs/0.61/datepickerandroid

This PR replacing the deprecated DatePicker with @react-native-community/datetimepicker as recommended in official docs

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
Travis failed not in case of my changes.
Fixed linter errors in #3251

**Comment by alexandrtovmach** [comment]
@hanykumar ping

**Comment by alexandrtovmach** [comment]
Ping

**Comment by webuijorgeGL** [comment]
Any update about this issue?

**Pull request merged**
