### PR TITLE
Fix request animation call, fixes #3206

### LINKED ISSUE #3206: this.requestAnimationFrame is not a function appears when going in and out of fullscreen mode
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
When playing a video in our app and we go in and out of fullscreen mode the simulator throws the error ```this.requestAnimationFrame is not a function```
When using a prior version of native-base (2.13.12) this bug did not exist in our app. Once we upgraded to native-base version 2.13.13, the bug started to appear. 

We've forked the Native-base repo and implemented the following workaround in the node_modules/native-base/src/basic/Tabs/index.js file:

Screen Shot 2020-07-29 at 3 09 21 PM

And in the node_modules/native-base/dist/src/basic/Tabs/index.js file:

Screen Shot 2020-07-29 at 3 14 27 PM

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: 10.15.3
react-native: 0.60.0
react: 16.8.6
native-base: 2.13.13
xcode: 11.1 (11A1027)

#### Expected behaviour
Should not throw an error when going in and out of fullscreen mode

#### Actual behaviour
throws an error when going in and out of fullscreen mode
Screen Shot 2020-07-29 at 2 58 57 PM

#### Steps to reproduce
Launch app and play a video
Then click fullscreen button to play video in fullscreen mode

#### Is the bug present in both iOS and Android or in any one of them?
Yes, bug is present in iOS and Android.

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

### PR DESCRIPTION
**Pull request by dgeorgiev**
Hi guys,

There is an issue in the latest version for the tabs components - basically this - https://github.com/GeekyAnts/NativeBase/issues/3206

This PR fixes the call (removing this so it can use the react native polyfill) https://reactnative.dev/docs/animations#requestanimationframe

### CODE REVIEW

**Comment by iamnader** [comment]
Can we get this merged please?  Tabs are broken on the latest version.

**Comment by jpatricknola** [comment]
our app is getting this same problem with this.requestAnimationFrame is not a function, if this pr fixes it, would love to get this baby merged

**Comment by nawartamawi** [comment]
Looking forward for this fix to be in soon, thanks for your efforts.

**Comment by tadhglewis** [comment]
Any updates on this? thanks for PRing

**Comment by rdgoutiyama** [comment]
> Any updates on this? thanks for the PR, hoping it can be merged soon

Not working for me. I'm using react-native-video and crash when going fullscreen or changing screen orientation. My solution for the moment was to hide the <Tabs> (using Redux) when changing the orientation or entering fullscreen.

**Comment by dgeorgiev** [comment]
@rdgoutiyama are you sure the issue you are having is coming from native-base and not react-native-video?

**Comment by jpatricknola** [comment]
It seems this PR didn't work for our situation either, maybe because we have useNativeDriver: false option, not sure.   But what did work was to put ```this.requestAnimationFrame && ``` in front of the call to this.requestAnimationFrame

**Comment by dgeorgiev** [comment]
@jpatricknola well that just hides the error and based on the official documentation (https://reactnative.dev/docs/animations#requestanimationframe) the correct way is like the PR which works for me, not sure why it didn't work out for you.

**Comment by tadhglewis** [comment]
@dgeorgiev this fix works perfectly for me as well.

**Comment by pawelkoss** [comment]
The same error appears when rotating device, nativ-base 2.13.14

**Comment by KennedyKeinstein** [comment]
@dgeorgiev thanks a lot.that's work for me

**Review by MohammedAtif — APPROVED** [review]

**Review by suhaibkhater — APPROVED** [review]

**Comment by rdgoutiyama** [comment]
> @rdgoutiyama are you sure the issue you are having is coming from native-base and not react-native-video?

No, when i use Tabs and change screen orientation, crashes for me.

**Comment by rdgoutiyama** [comment]
> The same error appears when rotating device, nativ-base 2.13.14

Same error for me.

**Comment by Andrerm124** [comment]
It would be very helpful if this was merged in as we're currently facing this issue as well

**Review by tadhglewis — APPROVED** [review]

**Comment by akinolu52** [comment]
any update on this?

**Review by spaceboom73 — APPROVED** [review]

**Comment by shivrajkumar** [comment]
@dgeorgiev Can you just add the changes for the fix and remove the transpiled code changes.

**Comment by dgeorgiev** [comment]
@shivrajkumar done.

**Comment by crobinson42** [comment]
@shivrajkumar ☝️ ✅

**Comment by VanLaerAshley** [comment]
I get the same error with the last version from the moment I used Tabs. Any fixes yet?

**Comment by lcastillo88** [comment]
This just became an issue for us in our prod app. Not very happy customers. Switching to this branch version for now until merged :(

**Comment by gtaylor44** [comment]
This issue is also affecting our app. Using branched version until this is merged. 

image

**Comment by jiangts** [comment]
any reason why this isn't merged yet?

**Comment by pm-sharma** [comment]
@akhil-geekyants 
Why this isn't merged yet?
When this will be fixed?

**Comment by shaileshbaldaniya-gep** [comment]
@dgeorgiev I see only changes needed to fix is https://github.com/GeekyAnts/NativeBase/pull/3218/files#diff-8af4a6552dd86a21d0953a6339180895f3b6cb0fecbab26ce21763327b20dc47L280-L282.

But in this PR there are some indentation changes as well which is not necessary. May be that is stoping them to merge this PR. If possible can you revert other unrelated changes? That will surely increase chances of getting this merged 😄

**Pull request closed without merging**
