### PR TITLE
use react-native's StyleProp Generic Type

### PR DESCRIPTION
**Pull request by AtrisMio**
React-native provide a generic type of StyleProp, it can use falsy type in style array.

### CODE REVIEW

**Comment by andreialecu** [comment]
There is a type error in the new TypeScript 3.1.1 with all native-base Component style properties:

```
Type 'RegisteredStyle<ViewStyle | TextStyle | ImageStyle>' is not assignable to type 'ViewStyle | ViewStyle[]'.
  Type 'RegisteredStyle<ViewStyle | TextStyle | ImageStyle>' is not assignable to type 'ViewStyle[]'.
    Property 'length' is missing in type 'Number & { __registeredStyleBrand: ViewStyle | TextStyle | ImageStyle; }'.
```

I believe it is due to the mismatch of types that this PR should fix.

**Comment by ScreamZ** [comment]
Hope this work :)

**Comment by cmcaboy** [comment]
Is there a workaround for this?

**Comment by burtek** [comment]
> Is there a workaround for this?

`style={styles.yourStyle as any}` should do the trick

**Comment by svipben** [comment]
This should be definitely merged and released ASAP because it's impossible to use newer TS version like 3.1.* or 3.2.* which gives a lot of new features/fixes, etc.

@AtrisMio Could you rebase and fix the conflicts?

/cc @SupriyaKalghatgi

**Comment by developercode1** [comment]
Please merge this so that we can upgrade to newer typescript versions

**Comment by AtrisMio** [comment]
@svipben sorry for late reply, but I've been too busy lately. Please wait for a little while, that won't be too long. I will fix it

**Comment by svipben** [comment]
@AtrisMio No problem, thank you!

**Comment by svipben** [comment]
As I workaround you can use this one which gives autocomplete and you don't need to cast `any` to style.

1. Add these into your `tsconfig.json` file:

```
"compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "*": ["src/*", "typings/*"]
    }
},
"include": ["src/**/*", "typings/**/*"]
```

_In our project we have all our typings in `typings` dir, if you don't have any of typings dir you should create it._

2. Create a new file in `typings` dir called `native-base.d.ts` with this content: https://gist.github.com/svipben/082cb26d776664f3c2eb4a455a0a75bd

<hr>

@AtrisMio You can use my [gist](https://gist.github.com/svipben/082cb26d776664f3c2eb4a455a0a75bd) to solve conflicts if you want.

**Comment by SupriyaKalghatgi** [comment]
#2562

**Pull request closed without merging**
