### PR TITLE
fix: goToPage of Tabs

### PR DESCRIPTION
**Pull request by NazarYablonskiy**
https://github.com/GeekyAnts/NativeBase/issues/181

### CODE REVIEW

**Comment by NazarYablonskiy** [comment]
@sanketsahusoft Take a look on this, plz

**Comment by sanketsahusoft** [comment]
@NazarYablonskiy Do you have a use-case example for the same?

**Comment by NazarYablonskiy** [comment]
@sanketsahusoft I'm sorry. I don't understand your question. What do you mean?

In my app I need to change a page programmatically. I made a small changes to make possible to do that.

**Comment by sanketsahusoft** [comment]
@NazarYablonskiy How do you use this feature? I am asking for an example so that we can document this.

**Comment by NazarYablonskiy** [comment]
```
import React, {Component} from 'react';
import {Tabs, Text, View} from 'native-base';

export default class MyComponentWithTabs extends Component {

  someEventHnadler() {
    this._tabs.goToPage(0); //
  }

  render() {
    return (
      <Tabs ref={(c) => {this._tabs = c;}}>
        <View tabLabel="Tab 1">
          <Text>Tab 1</Text>
        </View>
        <View tabLabel="Tab 2">
          <Text>Tab 2</Text>
        </View>
      </Tabs>
    );
  }
}
```

**Comment by sankhadeeproy007** [comment]
Thanks a lot @NazarYablonskiy !

**Comment by phixtalk** [comment]
Thanks for this, but i have a rather different case though, the above code works when the button link to navigate is in the same component as the tab, but i have a button link inside another component called from the main tab component. Please how do i bind this to work. thanks

**Comment by akbari6776** [comment]
> someEventHnadler() {
>     this._tabs.goToPage(0);
>   }

TypeError: Cannot read property 'goToPage' of undefined

this is my button onPress :
`
onPress={this.TabChangeHnadler() }
`

**Pull request merged**
