### PR TITLE
update definitions for nativebase 0.5.22

### PR DESCRIPTION
**Pull request by mrphu3074**
- Updated component's properties follow NativeBase 0.5.22
- Added `<Fab/>`
- Avoid throwing errors when pass not defined properties. By add this snipet beblow interface
```js
/**
* For any props comming soon
*/
[key: string]: any;
```
Ex:
```jsx
<Button active>Label</Button>
// Or
<Tabs>
<View tabLabel="Tab 1" />
</Tabs>
```

### CODE REVIEW

**Comment by wcandillon** [comment]
@mrphu3074 This PR makes sense but I'm really worried about the introduction of `CommingSoonProps`, I think that it removes the benefits of using a type definition.

**Comment by mrphu3074** [comment]
@wcandillon You're right.
But for some cases:
```jsx
<Text note>

OR

<Button badgeValue={2} badgeValueStyle={{ color: '#fff' }}>
  <Icon name="apps" />
  <Text>Apps</Text>
</Button>

OR 

<FooterTab>
  <Button>
      <Text>Apps</Text>
  </Button>
  <Button>
      <Text>Camera</Text>
  </Button>
  <Button active>
      <Text>Navigate</Text>
  </Button>
  <Button>
      <Text>Contact</Text>
  </Button>
</FooterTab>
```

Props `active`, `badgeValue`, `note` are undefined, so Typescript will throw error.

How to solve that.

**Comment by sagax85** [comment]
any plans/update on this one? Seems to fix plenty open typing errors I still have. Or should I prepare a separate one with the missing props/types?

It seems that the blocking factor here is the usage of 
```
[key: string]: any;
```

**Comment by wcandillon** [comment]
@sagax85 Unfortunately these typings are not up to date with version 2.0 of Nativebase. Could you contribute changes to this file?

**Comment by mrphu3074** [comment]
`Or should I prepare a separate one with the missing props/types?`
This can solve version 0.5.22. We can list all missing props/types and fix it. But in V2, it very open to using custom props.
Ex:
```jsx
// custom style
{
  "NativeBase.Button": {
    "customStyle1": {
      backgroundColor: "red"
   }
  }
}
```

```jsx
<Button styleName="customStyle1">
    <Text>My Button</Text>
<Button>

// case 2

<Button customStyle1>
    <Text>My Button</Text>
<Button>
```
So `[key: string]: any;` is quite fine

**Comment by shivrajkumar** [comment]
Closing this as most of the type definitions are added in v2.x and we are adding more as we find. Some of the use cases have changed since the PR. If you come accross any missing types, you can submit a new PR for the latest of NativeBase

**Pull request closed without merging**
