### PR TITLE
Fix initialPage for Tabs

### PR DESCRIPTION
**Pull request by tiberiumihai**
InteractionManager.runAfterInteractions(f) happen to sometimes never call f. Specially in DEV mode.

For more info check: [https://github.com/facebook/react-native/issues/8624#issuecomment-231040370](https://github.com/facebook/react-native/issues/8624)

### CODE REVIEW

**Comment by SupriyaKalghatgi** [comment]
@tiberiumihai Seems like you did not go through Contribution Guidelines

Please check it and update your code

**Comment by SupriyaKalghatgi** [comment]
You cannot edit code in `dist`

**Comment by tiberiumihai** [comment]
My bad. I'll update the PR.

**Comment by SupriyaKalghatgi** [comment]
@tiberiumihai Any updates on this

**Comment by tiberiumihai** [comment]
I used the contributing guideline to also test this.

This should be solved now.

Gif Demo - NativeBase: Fix Initial Tab

**Comment by ecnaidar** [comment]
@tiberiumihai 
Fix works in simple test case (still incorrectly renders in debug mode, though).
In the actual application does not work for both debug and release

Issue is rather frustrating and apparently somewhere deep in RN, since I was able to follow call to scrollTo in Interaction Manager. Correct values are going through up to the place where it is bridged to native module aaand ✨magically✨ nothing happens.

**Comment by tiberiumihai** [comment]
What do you mean "in simple test case"?
Do you have another use case in which this fix doesn't work?

Try to increase the InteractionManager's setTimeout time, probably your app is not so responsive due to some js processing and it needs more time to run the function.

**Comment by ecnaidar** [comment]
@tiberiumihai Just several tabs with text.
I have tried fiddling with timeout time, did not help. I suspect that animations in higher component hierarchy are interfering.

**Comment by ecnaidar** [comment]
#1443 This fixes issue for my specific case so apparently it makes situation better but certainly not fixes the issue

**Comment by SupriyaKalghatgi** [comment]
@tiberiumihai can you check from branch `development` if `initialPage` works as expected?

**Comment by SupriyaKalghatgi** [comment]
@tiberiumihai Indicator issue in case of changing `initialPage` value while hot reload

**Comment by aliwesome** [comment]
this issue is not fixed yet!

**Pull request merged**
