### PR TITLE
fix(icon): icons with theme not showing

### LINKED ISSUE #2832: Icons not working (showing ? instead)
Hello,

With those versions on windows 10 64bits: 
"native-base": "2.12.2",
"react-native": "0.60.4",
"react-native-vector-icons": "6.6.0" -> (i know that this is not the dev-depedencie 6.1.0 but it works with NB 2.12.1)

Icons are displayed with '?' instead of the good one (fontAwesome for my case)
If i downgrade to "native-base": "2.12.1" it works well..

What about NativeBase working with RN 0.60.x and the fact that linking process is no longer needed with RN 0.60.x ?

I've replaced my custom theme with the native-base one (using node node_modules/native-base/ejectTheme.js) without changing a line but it does'nt solve my isssue.

### PR DESCRIPTION
**Pull request by craftzdog**
`this.context` is always `undefined` in `constructor` method.
That causes icons not showing with theme.
Use `context` argument instead.

fix #2832

### CODE REVIEW

**Comment by tmaly1980** [comment]
@craftzdog Can you look at why the merge is failing?

**Comment by craftzdog** [comment]
There is no conflict to merge.
Tests are failing though, I guess this commit has nothing to do with them.

**Comment by tmaly1980** [comment]
Can someone look into the Travis CI system setup as to why this error is happening?

> react-native: command not found

This is causing errors with the checks, and I'm guessing the failed checks is keeping someone from actually wanting to merge into master. This was submitted almost 2 weeks ago!

**Comment by craftzdog** [comment]
why not merged? Looks like the CI issue has been solved.

**Comment by shivrajkumar** [comment]
@craftzdog Can you resolve the conflicts for us to merge this

**Comment by craftzdog** [comment]
@shivrajkumar Sure, done!

**Comment by craftzdog** [comment]
Please merge it.

**Pull request closed without merging**
