### PR TITLE
Attempt to fix header padding issue on iphoneX.

### PR DESCRIPTION
**Pull request by akhil-geekyants**
Fix for #1985 (Header clipped on iPhoneX)

### CODE REVIEW

**Comment by xstable** [comment]
Question to this fix: 
It is fixed in 2.5.2, but not still in 2.6.1 [current master]: 
 (https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Header.js)

Why is this?

**Comment by SupriyaKalghatgi** [comment]
This is with latest NativeBase 
image

**Comment by xstable** [comment]
For me it looks like this on IphoneX Emulator: 

image

**Comment by xstable** [comment]
If I had a look in node_modules/native-base/package.json I see 
image

**Comment by SupriyaKalghatgi** [comment]
Not sure, why its not working for you
Can you try with latest NativeBase?

**Comment by Darkilen** [comment]
Hello, i have the same screen than @xstable : 
capture d ecran 2018-12-12 a 18 39 23

With native-base 2.7.0
react-native 0.56.0
react 16.4.1

**Pull request merged**
