### PR TITLE
Web compatibility: Add generic (none android or ios) component files

### PR DESCRIPTION
**Pull request by remon-georgy**
This is an attempt to make NativeBase at least usable with react-native-web.

Currently, some js files are have ios.js or android.js extension, while lacking a generic .js alternative. This is an issue while using RNW because it attempts to load `*.js` or `*.web.js`.

This PR introduces the following, generic components. Note that they're copied from either iOS or Android components, whichever is more generic.

```
src/basic/Picker.js
src/basic/Tabs/Button.js
src/theme/components/Picker.js
``` 

Note that even after merging this PR, NB still errs out on web because of some issues that are tackled in separate PRs (see #1359). Also this [react-native-easy-grid PR](https://github.com/GeekyAnts/react-native-easy-grid/pull/53).

### CODE REVIEW

**Comment by micimize** [comment]
I had similar [react-native-web usage issues](https://github.com/GeekyAnts/NativeBase/issues/1244#issuecomment-350139410). @remon-georgy, were you able to get any components rendering properly?

**Comment by PeterKottas** [comment]
Is there any progress with this? Is the package currently compatible with react-native-web?

**Comment by PeterKottas** [comment]
I managed to make it work on my own but I am afraid I've got some bad news. It doesn't seem likely this lib will support web properly in the near future. Basically every component is throwing all sorts of warnings. Most stuff is not styled properly. It would indeed require A LOT of work and I am not sure if the priority for authors lies this way.

**Comment by micimize** [comment]
@PeterKottas I've been working off of [my fork](https://github.com/micimize/NativeBase) for a while now ([earlier comment](https://github.com/GeekyAnts/NativeBase/issues/1244#issuecomment-353684860), [config info](https://gist.github.com/micimize/bf64ecbb6a32c236534a3431e76b27bb))
It also points to [my patched `native-base-shoutem-theme`](https://github.com/micimize/theme) that allows for the use of the original shoutem `styleNames='large success'` syntax to avoid the warnings about invalid `true` props passed to the DOM. 

In the short term you could develop off of the latest there with
`"native-base": "git://github.com/micimize/NativeBase.git#bbaf404e3e5b89392ed46cac9725d43e46cd35d5"`

**Comment by PeterKottas** [comment]
Thanks man, I ended up with similar config and yes it "worked" but some components are unusable, the warnings are annoying (yes you can filter it but still). I'd rather build something in-house probably borrowing a lot of code here and there rather then relying on this which was clearly not build with web in mind. No wonder as web was not around by then, but it seems this will be path of least resistance. Hopefully it will one day be picked up and handled properly :)

**Comment by SupriyaKalghatgi** [comment]
@PeterKottas You can check [NativeBase-Customizer](https://github.com/GeekyAnts/NativeBase-Customizer) for working example of NativeBase for web, though it has some customizations done

Very soon, NativeBase will support NativeBase  for Web extensively

**Comment by PeterKottas** [comment]
Good to hear that! Are there any timelines in mind?

**Comment by geminiyellow** [comment]
@PeterKottas good news , but how soon ?

**Comment by SupriyaKalghatgi** [comment]
Pushed on master

**Comment by geminiyellow** [comment]
:clap:

**Pull request closed without merging**
