### PR TITLE
fix security issues / vulnerabilities reported by npm audit

### PR DESCRIPTION
**Pull request by BlueT**
I've got a lot of security warning emails from projects using NativeBase.

Summary:
1. Bump dependency versions to patched version.
2. `npm run lint` and `npm run traspile` pass.

### CODE REVIEW

**Comment by BlueT** [comment]
@PlabanJr @tamurayk @IntelliJAbhishek  please kindly review, and if it's ok, expecting to have it published as new version on npmjs to solve security issues. Thanks!

**Comment by PlabanJr** [comment]
Looks good to me. But kindly update the `react-native-vector-icons` to the latest version as well. With your changes and the current version of `react-native-vector-icons`, the app crashes.

**Comment by IntelliJAbhishek** [comment]
LGTM

**Comment by tamurayk** [comment]
LGTM

**Comment by BlueT** [comment]
@PlabanJr @tamurayk @IntelliJAbhishek Can anyone merge the PR and publish a new release to npmjs to solve security issues. Thanks!

**Comment by IntelliJAbhishek** [comment]
@BlueT sorry I'm not from native base team. I don't have access.

**Comment by BlueT** [comment]
@sankhadeeproy007 thank you for the merge.
Can we expect a new release publish to npmjs anytime soon? :-)

**Pull request merged**
