### PR TITLE
Resolved "Accordion multiple items" pull request's merge conflicts

### PR DESCRIPTION
**Pull request by littlefinger42**
@flodev created a pull request implementing the ability to open multiple accordion items at once.
Unfortunately he never got the time to resolve the merge conflicts. The pullrequest was left to get stale since august.

I've resolved the conflicts.
Note, I also ran "yarn" and it gave me looooads of changes. Maybe because i'm on windows?

https://github.com/GeekyAnts/NativeBase/pull/2632

I haven't changed anything from his original approved code, apart from resolving the conflicts.

### CODE REVIEW

**Comment by littlefinger42** [comment]
Also, when i merged master into this branch I was unable to build because of linting issues in other files?

**Comment by littlefinger42** [comment]
Linting issues solved in https://github.com/GeekyAnts/NativeBase/pull/3055

**Comment by littlefinger42** [comment]
Can a reviewer look at this and the linting fix please?

**Comment by keithmattix** [comment]
I'd love to use this feature in my project; is this being looked at?

**Comment by clivewatts** [comment]
Any movement on this? This is a much neaded feature for us

**Comment by littlefinger42** [comment]
I've requested reviewers on my MRs for some time but no response from @nativebase yet. 
Is there something wrong in my request?

**Comment by sankhadeeproy007** [comment]
This branch has some conflicts with the master branch. 
Please update this PR to include only the files which have been changed. The transpilation step can be skipped while creating PR's.
Thank you for this PR.

**Comment by shivrajkumar** [comment]
Closing this as a similar PR #3212 with resolved issues has been merged

**Pull request closed without merging**
