### PR TITLE
Adding long presss event support to ListItem

### PR DESCRIPTION
**Pull request by mortezaalizadeh**
Hi, I am using NativeBase in my own personal project and came down to implement a requirement on my app two days ago where I found out long press event is not support by ListItem. Here is the change that add that capability to the ListItem. Cheers, Morteza

### CODE REVIEW

**Comment by sankhadeeproy007** [comment]
Thanks!

**Comment by mortezaalizadeh** [comment]
When will you release the onLongPress change? Would be great if I can use soon in my project. ;-)

**Comment by Symous** [comment]
Hello,I edited the source code in my own project,but it still not working when I do LongPress on ListItem.

**Comment by mortezaalizadeh** [comment]
@Symous , share your code here, let me know how you have done it :)

**Comment by Symous** [comment]
I edited the ListItem.js in native-base/src/basic.just totally same as yours.

```js
import React, { Component } from 'react';
import { TouchableHighlight, Platform, TouchableNativeFeedback, View } from 'react-native';

import { connectStyle } from '@shoutem/theme';
import mapPropsToStyleNames from '../Utils/mapPropsToStyleNames';
import variable from '../theme/variables/platform';

class ListItem extends Component {
  static contextTypes = {
    theme: React.PropTypes.object,
  }
  render() {
    const variables = (this.context.theme) ? this.context.theme['@@shoutem.theme/themeStyle'].variables : variable;

    if (Platform.OS === 'ios' || variable.androidRipple === false || !this.props.onPress || !this.props.onLongPress || Platform.Version <= 21) {
      return (
        <TouchableHighlight
          onPress={this.props.onPress}
          onLongPress={this.props.onLongPress}
          ref={c => this._root = c}
          underlayColor={variables.listBtnUnderlayColor}
        >
          <View {...this.props}>{this.props.children}</View>
        </TouchableHighlight>
      );
    }
    else {
      return(
          <TouchableNativeFeedback ref={c => this._root = c}
              onPress={this.props.onPress}
              onLongPress={this.props.onLongPress}
              background={(this.props.androidRippleColor) ? TouchableNativeFeedback.Ripple(this.props.androidRippleColor) : TouchableNativeFeedback.Ripple(variable.androidRippleColorDark)}>
              <View style={{ marginLeft: -17, paddingLeft: 17 }}>
                <View {...this.props}>{this.props.children}</View>
              </View>
          </TouchableNativeFeedback>
      );
    }
  }
}

ListItem.propTypes = {
  ...TouchableHighlight.propTypes,
  style: React.PropTypes.object,
  itemDivider: React.PropTypes.bool,
  button: React.PropTypes.bool,
};

const StyledListItem = connectStyle('NativeBase.ListItem', {}, mapPropsToStyleNames)(ListItem);

export {
  StyledListItem as ListItem,
};
```

**Pull request merged**
