### PR TITLE
Add transpilation step to ensure native-base works with Jest out of the box

### PR DESCRIPTION
**Pull request by dikarel**
**Changes**

- Add `npm run compile` command to transpile source into `dist` directory
- `npm publish` publishes the `dist` directory, the `Fonts` directory, and `index.d.ts`
- Ignore extraneous files on publish (images, config files, dotfiles)

Fixes the following issues: #396, #400

**Testing**

- Published as [native-base-transpiled](https://www.npmjs.com/package/native-base-transpiled) and used locally on a React Native project
- Verify via [unpkg](https://unpkg.com/native-base-transpiled@0.5.25/) that correct files are published

### CODE REVIEW

**Comment by sankhadeeproy007** [comment]
One small problem with this PR is that the `Fonts` directory doesn't get published with the package. Any idea why that might be happening?

**Comment by dikarel** [comment]
Thanks, good catch.

I forgot to add the fonts directory into package.json's "files" property.

Will send out a fix within 24h

**Comment by dikarel** [comment]
@sankhadeeproy007: I've made sure the fonts dir also gets published. You can verify below:

https://unpkg.com/native-base-transpiled@0.5.25/

**Comment by FDiskas** [comment]
Probably same goes to `native-base-shoutem-theme` dependency

**Pull request merged**
