### PR TITLE
Allow formatting of DatePicker chosen date text

### PR DESCRIPTION
**Pull request by jgable**
This commit adds an optional `formatChosenDate` prop to the DatePicker component. If the prop is not supplied this will fall back to the original chosen date text format. Feedback welcome on the name of the prop, other options could be `chosenDateFormatter` or maybe `chosenDateFormat`.

I also included some basic IOS and Android jest tests for the placeholder text, default chosen date format and custom chosen date format. This is my first time adding jest tests so feedback welcome if I've messed anything up.

Test Plan:

- Ran `eslint` on my changes to `DatePicker.js`
- Ran `yarn run jest DatePicker` and inspected the snapshots to ensure properly formatted placeholder text, default format text and custom format text.

### CODE REVIEW

**Comment by SupriyaKalghatgi** [comment]
@jgable We cannot accept test cases
Can you exclude it from your PR?

**Comment by SupriyaKalghatgi** [comment]
@jgable We will be closing this PR in a day in case of no response

**Comment by akhil-geekyants** [comment]
@jgable your PR solves #2056. Can you exclude the test files from your PR.

**Comment by vidit-bhatia** [comment]
Are we expecting this to be merged soon?

**Comment by vidit-bhatia** [comment]
@akhil-geekyants if the need is just to remove the tests added I can open a PR with those changes I need this functionality

**Comment by vidit-bhatia** [comment]
I also feel that this property must be exposed outside through the interface in the index.d.ts file

**Comment by vidit-bhatia** [comment]
@SupriyaKalghatgi @akhil-geekyants I wont be able to release my app without this fucntionality I can open a PR for the same if @jgable  is not interested to fix this

**Comment by SupriyaKalghatgi** [comment]
Check commit here https://github.com/GeekyAnts/NativeBase/commit/0b59fb7eab77c51b36508f3ba842911260426ffd

**Comment by cgomezmendez** [comment]
Wow this was exactly what I was lucking for, thanks you a lot, upgrading to 2.7.1

**Pull request closed without merging**
