### PR TITLE
implemented accordion multiple items open feature

### PR DESCRIPTION
**Pull request by flodev**
Hi,

awesome work with nativebase. Keep it up.
I've implemented multiple accordion items open feature and would be happy if you could apply the PR so that I can update my nativebase dependency and use the regular accordion.

Edit:
Ah maybe some details would be nice :)
The accordion accepts now a number or an array of numbers in the `expanded` property.
You will need to pass `expandMultiple` flag in order to have multiple items expanded. 
Otherwise the accordion sticks to one item expanded only.
This approach is fully backwards compatible so you can continue using it with one number only.
```
// expands first and second
<Accordion dataArray={dataArray} expanded={[0, 1]} expandMultiple />

// still valid, will expand one item at a time
<Accordion dataArray={dataArray} expanded={0} />

// also valid, will expand the first item
// expanded property will be used in a state array internally
<Accordion dataArray={dataArray} expanded={0} expandMultiple/>

// its valid you guessed it :)
// but will expand second item only
<Accordion dataArray={dataArray} expanded={[1,2]} />
```

### CODE REVIEW

**Comment by nyur321** [comment]
@flodev Thanks

**Comment by sankhadeeproy007** [comment]
LGTM, @flodev Can you please fix the conflicts?

**Comment by mushinz** [comment]
@sankhadeeproy007 can we get this conflicts solved and merged?

**Comment by flodev** [comment]
I don't have time unfortunately. Maybe in two weeks. Sorry.

**Comment by sytolk** [comment]
@flodev can you resolve the conflicts or let me cherry pick your commits in another PR?

**Comment by littlefinger42** [comment]
I resolved the conflicts in this PR
https://github.com/GeekyAnts/NativeBase/pull/3052

**Comment by datfc97pro** [comment]
@flodev You can fix it?

**Comment by pramodjb** [comment]
expand multiple accordion not working

**Review by pramodjb — APPROVED** [review]

**Comment by shivrajkumar** [comment]
Closing this as a similar PR #3212 has been merged

**Pull request closed without merging**
