### PR TITLE
update fonts fix bug unexpected icon #3213

### LINKED ISSUE #3213: Ionicons not rendering the expected icon
## I have gone through these following points

- [] Check latest documentation: https://docs.nativebase.io/
- [] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
Node: v12.18.3
npm: 6.14.6
React: 16.11.0
native-base: 2.13.13
expo: 38.0.0
#### Expected behaviour

According to: https://oblador.github.io/react-native-vector-icons/

Expecting icons `ios-grid` and `people` to be those (Ionicons family)
image

#### Actual behaviour

Getting those instead
image

#### Steps to reproduce

```
import {Icon} from 'native-base'

<Icon name="ios-grid" type="Ionicons" />
<Icon name="people" type="Ionicons" />
```

https://snack.expo.io/@pixcell/mad-coffee

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

### PR DESCRIPTION
**Pull request by alfianwahid**
Fixes #3213

### CODE REVIEW

**Comment by Arjanvanmaren** [comment]
Could this be merged please as the icons are currently not correct?

**Comment by alfianwahid** [comment]
> Could this be merged please as the icons are currently not correct?

I hope this can fixes #3213 and #3217

**Comment by jahead** [comment]
@shivrajkumar Are you able to merge this?
I know you everyone is busy with v3, but it's currently icons are broken icons on 0.63.

**Comment by williamgurzoni** [comment]
Looking forward to this merge as well. Thanks.

**Comment by TheRusskiy** [comment]
@shivrajkumar sorry to bother you, but if you have it would be great to get this merged

**Pull request merged**
