### PR TITLE
Fixes #3273

### LINKED ISSUE #3273: Error: currentlyFocusedField is deprecated
ReactNative version: 0.63.2
Expo version: 39.0.0
NativeBase version: 2.13.14
Test Platform: iOS 

 When an `Input` in `Content` component **gets focus** and the **keyboard pops up**, an error message will appear: `currentlyFocusedField is deprecated and will be removed in a future release. Use currentlyFocusedInput`

I think it should be caused by `@codler/react-native-keyboard-aware-scroll-view`

https://github.com/GeekyAnts/NativeBase/blob/0315c117959bf19eae0f7c2a85e7faafa982f6e9/src/basic/Content.js#L5

### PR DESCRIPTION
**Pull request by mbeech**
Update to the latest version of @codler/react-native-keyboard-aware-scroll-view to fix depreciated currentlyFocusedField
https://github.com/GeekyAnts/NativeBase/issues/3273

### CODE REVIEW

**Comment by summerkiflain** [comment]
please merge this and publish soon.

**Comment by getumangon** [comment]
Please merge this and publish ASAP. This one was fixed since last three months still not merged.

**Comment by shivrajkumar** [comment]
A pr fixing this has already been merged

**Comment by mbeech** [comment]
Thanks https://github.com/GeekyAnts/NativeBase/commit/853c63c8c562f09951a31d842361ce7e90383b2b#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Pull request closed without merging**
