### PR TITLE
WIP Convert to typescript

### PR DESCRIPTION
**Pull request by FDiskas**
Help needed :)

### CODE REVIEW

**Comment by FDiskas** [comment]
Also take a look at https://github.com/GeekyAnts/NativeBase-KitchenSink/pull/182

**Comment by juandav** [comment]
I like the idea of passing the code to typescript

**Comment by FDiskas** [comment]
this also reveals allot of bugs, but currently its not possible for me to know is it made with purpose or by mistake

**Comment by FDiskas** [comment]
Thanks

**Pull request closed without merging**
