### PR TITLE
Fix - Modifying the assertion on the "Item" component to use the "displayName"prop

### PR DESCRIPTION
**Pull request by gvarandas**
Changing the verification of types to use the "displayName" prop instead of the pure type.
This allows Higher Order Components to be used inside the Item component and behave exactly like original components by just setting their "displayName" accordingly.
The same behavior already exists on the "componentWillReceiveProps" lifecycle.

Also optimized the children verification on the "_renderChildren_" method to run across all children only once instead of one time for each component group (Label, Input and Icon).

The need for this modification came from the need to insert a mask on the "Input" component, which was accomplished by the use of a Higher Order Component.
This, on the other hand, changed the type of the Input to the "_MaskedInput_", which was the HOC type and by doing so, the floating label item stopped to recognize the "_inputProps_" and to pass them through to the Input child.

Feel free to comment and I'll be happy to contribute more. 🤖

### CODE REVIEW

**Comment by gvarandas** [comment]
After reading the Contribute Guidelines, I'm still confused if whether should I commit the dist files generated after the transpile task or not.
I'll update accordingly if necessary. 🤖

**Comment by akhil-geekyants** [comment]
@gvarandas just checked this PR against the example in #2011. Updating the HOC Input didn't change the state. Can you check this.

**Comment by gvarandas** [comment]
@akhil-geekyants just updated the example.
I've forgotten to set the displayName of the HOC.

Please verify again. 🤖

**Comment by gvarandas** [comment]
Actually, I've just realized that theres still a problem with the HOC assertion because the "Item" component changes its type.
I'll update the PR and comment here when ready.

**Comment by gvarandas** [comment]
@akhil-geekyants the PR is updated with some optimizations and corrections.

- Kept the child types immutable, allowing the HOC to function properly whenever inserted as children of the Item component;
- Optimized the rendering loop inside the "renderChildren" method;

Please review again. 🤖

**Comment by gvarandas** [comment]
@akhil-geekyants @SupriyaKalghatgi any news on this?

**Comment by akhil-geekyants** [comment]
@gvarandas just checked this. Didn't work for me. Can you create a test repo for us to check (pointing native-base to this branch)

**Comment by gvarandas** [comment]
@akhil-geekyants sure. Will publish and link the repo here soon enough.
Thank you.

**Comment by SupriyaKalghatgi** [comment]
@gvarandas Any updates on this?

**Comment by gvarandas** [comment]
@SupriyaKalghatgi sorry for the delay. Was having a busy week. 🚀 

Noticed that my last commit on the PR was missing the updated "dist" files, which probably caused the confusion. Just fixed that and created the [configured repo](https://github.com/gvarandas/NativeBaseLab) with the proposed solution working.

Feel free to reach me up. 🤖

**Comment by SupriyaKalghatgi** [comment]
@gvarandas One more step needed before merging this PR
Your code quite old, since we had 5 releases after you submitted this PR
Please pull the latest from `master` and update the PR
Also you can skip `transpile`

**Comment by gvarandas** [comment]
@SupriyaKalghatgi done! Please check it out. 🤖

**Comment by SupriyaKalghatgi** [comment]
@gvarandas This PR fixes #2011 
But fails in case of icons with Floating label

This is with existing code of `Item.js`
image

This is with code from your PR
image

**Comment by SupriyaKalghatgi** [comment]
this should be the last commit probably
looks fine to me

**Comment by gvarandas** [comment]
@SupriyaKalghatgi is this going to get merged? We're waiting for a new release to correct a production bug. 🤖

**Comment by SupriyaKalghatgi** [comment]
yes, this week

**Comment by SupriyaKalghatgi** [comment]
#2264 issue due to this PR, reverting this

**Pull request merged**
