### PR TITLE
Tabs not using react-timer-mixin

### PR DESCRIPTION
**Pull request by dgarciamuria**
Currently, `Tabs` implementation applies `react-timer-mixin` but the `setTimeout` in `componentDidMount` is not using it since it should be `this.setTimeout`. In consequence, there might be cases where that callback gets fired and when the component is already unmounted. I hit that error my self, were `scrollView` was null and it was trying to call `.scrollTo`

Cheers!

### CODE REVIEW

**Comment by FDiskas** [comment]
But the bad thing is that this module https://calendar.perfplanet.com/2019/the-unseen-performance-costs-of-css-in-js-in-react-apps/ is deprecated

**Comment by FDiskas** [comment]
if you want to remove mixin component should be refactored to react class and timer should be assigned to private variable and on unmount timeout should be cleared

**Comment by sankhadeeproy007** [comment]
@dgarciamuria @FDiskas What's the status with this one? Can this be merged?

**Comment by FDiskas** [comment]
@sankhadeeproy007 it can be merged. Later it should be refactored and unmaintained mixin removed.

**Comment by dgarciamuria** [comment]
@FDiskas I refactored and removed the mixin dep. Wasn't sure if needed to run the `prepublish` script or not, but that was the only way to update the `dist` directory. Let me know if that's correct since now IconNB is in conflict.

Thanks!

**Comment by FDiskas** [comment]
I suppose the dist directory should be touched by the owners and only before releasing new version. So in this case only files in src directory should be changed.

**Comment by dgarciamuria** [comment]
@FDiskas cool. I just reverted that piece

**Comment by FDiskas** [comment]
There is something strange is going on in `yarn.lock` file.

**Comment by dgarciamuria** [comment]
@FDiskas mmm, it seems that `yarn.lock` has been out of sync for a while, so after running `yarn remove react-timer-mixin` it got re generated. Same thing happens when running `yarn install`. But anyways I reverted `yarn.lock`

**Comment by FDiskas** [comment]
@sankhadeeproy007 ready steady go :)

**Pull request merged**
