### PR TITLE
fix(Toast) : useReactNative warning fixed on swipe

### PR DESCRIPTION
**Pull request by hanykumar**
#3109 
Warning Fixed
`Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false``

### CODE REVIEW

**Review by alexandrtovmach — CHANGES_REQUESTED** [review]
please do not add comma at the line end

**Comment by hanykumar** [comment]
@alexandrtovmach , auto-save does this.

**Comment by alexandrtovmach** [comment]
@hanykumar yes, I understand, but it's your local prettier config, not repo

**Comment by hanykumar** [comment]
duplicate #3221

**Pull request closed without merging**
