### PR TITLE
explicitly set isFocused to false in Item floatingLabel

### LINKED ISSUE #1605: floatingLabel input doesn't "unfloat" after setting value with input blurred
## react-native, react and native-base version
react: 16.2.0, react-native: 0.53.0, native-base: 2.3.9

## Expected behaviour
When an Input within a floatingLabel Item has its value cleared programmatically, the label should "unfloat".

## Actual behaviour
The label remains floating above.

## Steps to reproduce (code snippet or screenshot)
```
import React, { Component } from 'react';
import { Container, Header, Content, Form, Item, Input, Label } from 'native-base';
export default class FloatingLabelExample extends Component {
  constructor() {
    super();
    this.state = {
      username: '',
    };
    setTimeout(() => {
      this.setState({ username: 'foo' });
      setTimeout(() => {
        this.setState({ username: '' });
      }, 2000);
    }, 5000);
  }
  render() {
    return (
      <Container>
        <Header />
        <Content>
          <Form>
            <Item floatingLabel>
              <Label>Username</Label>
              <Input value={this.state.username} />
            </Item>
          </Form>
        </Content>
      </Container>
    );
  }
}
```

## Screenshot of emulator/device
image

## Is the bug present in both ios and android or in any one of them?
Present on both.

## Any other additional info which would help us debug the issue quicker.
Can be fixed by explicitly setting "isFocused: false" in Item's componentDidMount and componentWillReceiveProps.  PR coming soon.

### PR DESCRIPTION
**Pull request by rizzomichaelg**
fixes #1605

### CODE REVIEW

**Comment by rizzomichaelg** [comment]
fixes #1079

**Comment by SupriyaKalghatgi** [comment]
@rizzomichaelg i dont find this PR fixing the issue

Can you share GIF of code along with working example?

**Comment by rizzomichaelg** [comment]
```
export default class App extends React.Component {
  constructor() {
    super();
    this.state = {
      email: '',
    };
    this.onSubmit = this.onSubmit.bind(this);    
  }
  onSubmit() {
    this.setState({ email: '' });
  }
  render() {
    return (
      <Container>
        <Header />
        <Content>
          <Form>
            <Item floatingLabel>
              <Label>Email</Label>
              <Input
                value={this.state.email}
                onChangeText={email => this.setState({ email })}
              />
            </Item>
          </Form>
          <Button full onPress={this.onSubmit}>
            <Text style={{ color: 'white' }}>
              Submit
            </Text>
          </Button>
        </Content>
      </Container>
    );
  }
}
```
Broken:
broken

Fixed in this PR:
fixed

**Comment by SupriyaKalghatgi** [comment]
@rizzomichaelg Sorry to inform you that, we are reverting this PR in favor of fixing #2000

**Pull request merged**
