### PR TITLE
added missing useNativeDriver:false to DeckSwiper, Fab, and ToastContainer components.

### PR DESCRIPTION
**Pull request by copleykj**
Seems like useNativeDriver was missed in a few places for #3136.

### CODE REVIEW

**Comment by copleykj** [comment]
Originally this PR was just for the DeckSwiper component as that is what I was having issues with personally. I've since stumbled upon other issues that are experiencing this error for other components and so I'll be adding to this PR.

Will remove WIP from title when finished.

**Comment by summerkiflain** [comment]
Please merge this and publish the new version on npm, huge request, hate those warnings on expo sdk 39.

**Comment by ticoprogrammer** [comment]
Is it already published on npm ? Im using 2.13.14 and im having that issue with FAB.

**Comment by copleykj** [comment]
I think that some other PRs have been merged that fix some of the issues that this PR addresses, but I don't believe any have been published as of yet.

**Comment by copleykj** [comment]
That being said, this PR also fixes issues that were not addressed in those other PRs that have been merged.

**Pull request merged**
