### PR TITLE
Added TimePicker

### PR DESCRIPTION
**Pull request by akhil-geekyants**

### CODE REVIEW

**Comment by SupriyaKalghatgi** [comment]
timepicker

**Comment by slavikdenis** [comment]
This seems promising! What's blocking it?

**Comment by viniciusbo** [comment]
This would be really useful.

**Comment by allan-simon** [comment]
Is it blocked because the CI is not passing ? if so it seems to not be because of the PR itself (the CI fails with "yarn test : test command not found"

**Comment by shivrajkumar** [comment]
We are not adding any new components to the current version of NativeBase for now.

More details on #3069

**Pull request closed without merging**
