### PR TITLE
Added H4, H5 & H6 to Typography

### PR DESCRIPTION
**Pull request by akhil-geekyants**
Issue #2081 ([FEATURE REQUEST] More Typography Style)

### CODE REVIEW

**Comment by mnlbox** [comment]
@akhil-geekyants Please also add more Typography. You can see https://github.com/hectahertz/react-native-typography for some idea.

**Comment by mnlbox** [comment]
@SupriyaKalghatgi Why close? :thinking:

**Comment by SupriyaKalghatgi** [comment]
This was giving less freedom to customize or you can say, not ease of use
I will add them some time soon with better flexibility

**Comment by mnlbox** [comment]
OK, I'm waiting for it. So can you please refer to related PR here? (better implementation that you said)

**Comment by mnlbox** [comment]
@SupriyaKalghatgi Any news?

**Comment by mnlbox** [comment]
@SupriyaKalghatgi Any news?

**Pull request closed without merging**
