### PR TITLE
Toast bug fix

### PR DESCRIPTION
**Pull request by ilya-bmi**
Fix non-working buttons in IOS after displaying the toast.

### CODE REVIEW

**Comment by summerkiflain** [comment]
This should be merged ASAP, and npm should be updated.

**Comment by yaron1m** [comment]
@sankhadeeproy007 Can you please review this important bug fix?

**Comment by yaron1m** [comment]
@sankhadeeproy007 Can you please publish this bug fix?

**Comment by maximeBAP** [comment]
@sankhadeeproy007 when is the release of this bug fix planned ?

**Pull request merged**
