### PR TITLE
ViewPropTypes error fix in src/basic/Tabs/

### PR DESCRIPTION
**Pull request by matias91**
Using **NativeBase** with `react-native-web` latest version crashes the app because `ViewPropTypes` is undefined:

Screen Shot 2020-10-20 at 11 03 04

I found this solution in different repos with the same issue.

Related issues:
https://github.com/GeekyAnts/NativeBase/issues/3083
https://github.com/GeekyAnts/NativeBase/issues/3130
https://github.com/GeekyAnts/NativeBase/issues/3231
https://github.com/GeekyAnts/NativeBase/issues/3264

### CODE REVIEW

**Comment by NishargShah** [comment]
any update on this?

**Comment by piccinnigius** [comment]
i think that nativebase needs some maintainers.. if needed i can do this!

**Comment by mratzka** [comment]
I can reproduce this issue! nice little blocker :(

**Comment by nathan-remote** [comment]
Is there any estimate as to when this PR will be merged? 

This is currently a blocker for us

**Comment by MohammadAzimi** [comment]
when is it going to be merged and released? It's about two months since the related issues created :(

**Comment by MohammadAzimi** [comment]
I made a repo to fix this issue temporarily which is depend on this pull request
`npm i @red-elephant/native-base`

**Comment by adderly** [comment]
Hopefully this will be merge soon.

**Comment by GSingh01** [comment]
@matias91 looks like this branch has conflicts. 
@theankurkedia @akhil-geekyants @rohits-geekyants can you please merge the PR after conflict resolution.
Thanks

**Comment by matias91** [comment]
@GSingh01, branch updated with conflicts solved.

**Comment by shivrajkumar** [comment]
@matias91 There seems to be a lot of linting changes, due to which it's difficult to review and merge this PR. Could a create a PR with just the required changes or update this one with the same

**Comment by tyrauber** [comment]
@shivrajkumar This was a blocker for us as well, so I took a look. I took a slightly different approach in #3336 inspired by @matias91.  I modified `src/utils/index.js` to remove the ViewPropTypes 'react-native' import and replace it with:

```
const ViewPropTypes = {
    style:  PropTypes.shape({
        style: PropTypes.any,
    })
}
```

No other change is necessary. Fix works with Expo Web (~40.0.0).

**Comment by matias91** [comment]
@shivrajkumar, it seems this changes are already in master...
Probably someone merged another PR with these fixes.
I'll close this one.

**Pull request closed without merging**
