### PR TITLE
fix: error->importing picker from react-native core is deprecated

### PR DESCRIPTION
**Pull request by Simranjit1080**
imported picker from @react-native-community/picker

### CODE REVIEW

**Review by alexandrtovmach — CHANGES_REQUESTED** [review]
It's incorrect way to import `Picker`. Should be named import:
```ts
import { Picker } from '@react-native-community/picker';
```

See example from docs:
https://www.npmjs.com/package/@react-native-community/picker#usage-1

**Comment by alexandrtovmach** [comment]
@akhil-geekyants @sankhadeeproy007 @SupriyaKalghatgi @shivrajkumar
Pay attention to this PR, because it seems like urgent

**Comment by Simranjit1080** [comment]
> It's incorrect way to import `Picker`. Should be named import:
> 
> ```ts
> import { Picker } from '@react-native-community/picker';
> ```
> 
> See example from docs:
> https://www.npmjs.com/package/@react-native-community/picker#usage-1

fixed the imports.

**Comment by bb128b** [comment]
I have started a new project and it's causing me issues with this error.

` ERROR    Warning: Picker has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/picker' instead of 'react-native'. See https://github.com/react-native-community/react-native-picker`

**Review by sankhadeeproy007 — APPROVED** [review]

**Review by alexandrtovmach — APPROVED** [review]

**Comment by alexandrtovmach** [comment]
@shivrajkumar Thanks for merging :+1: How about making release and publish it to NPM?

**Comment by alexandrtovmach** [comment]
Friendly reminder :top: 
@akhil-geekyants @sankhadeeproy007 @SupriyaKalghatgi @shivrajkumar

**Comment by alexandrtovmach** [comment]
Ping

**Comment by alexandrtovmach** [comment]
Please
@akhil-geekyants @sankhadeeproy007 @SupriyaKalghatgi @shivrajkumar

**Comment by fdkitlui** [comment]
It's almost there.
node_modules/native-base/package.json

"main": "dist/src/index.js",
changed to:
"main": "src/index.js",

reason:
don't use dist folder as main, use the src folder instead, so that the previous fixes would actually work.
(the compiled dist folder is old, however, if we run "npm run prepublish && npm run postinstall" to update the dist folder, the app would fail when launch.)

solutions:

in ourAppProject/package.json

"native-base": "^2.13.14",
changed to:
"native-base": "https://github.com/fdkitlui/NativeBase.git",

or

fork https://github.com/GeekyAnts/NativeBase.git to your own git
and change "main" entrance in native-base's package.json, push to your own git
in ourAppProject/package.json
change "native-base" to your git address

cd ourAppProjectPath 
rm -rf node_modules
yarn install

**Comment by GeorgS** [comment]
Any ETA for a new release containing this change?

**Comment by alexandrtovmach** [comment]
Guys, I don't want to be annoying, but could you make a release?
@akhil-geekyants @sankhadeeproy007 @SupriyaKalghatgi @shivrajkumar

P.S. CI/CD can resolve this issue by automatically deploy and release after merging to `master`

**Review by leandroasilva — COMMENTED** [review]
ok

**Comment by prasanthsd** [comment]
Can we please have an update on the release?

**Comment by alexandrtovmach** [comment]
We're waiting for two months just for making a release to NPM. Why it's so hard? Give me a contributor rights, so I can do that, because seems like nobody cares about this project from the core team.
@akhil-geekyants @sankhadeeproy007 @SupriyaKalghatgi @shivrajkumar

**Comment by billnbell** [comment]
common!!!!!!!!!!!!!

**Comment by alexandrtovmach** [comment]
Ping

**Comment by billnbell** [comment]
Ping again. Can someone please fix this?

**Comment by arochedy** [comment]
Now it's @react-native-picker/picker and not  '@react-native-community/picker' anymore :( 

Any plan to update to this new library ?

**Comment by alexandrtovmach** [comment]
Ohhh, really? Again renamed... That's why I don't like react native, no any stability

**Comment by arochedy** [comment]
Yes I don't understand why it's change so frequently. It looks like there is no more projetc in react-community

**Comment by alexandrtovmach** [comment]
@arochedy if you can make a PR it'll be great :+1:

**Comment by armanatz** [comment]
> Now it's @react-native-picker/picker and not '@react-native-community/picker' anymore :(
>
> Any plan to update to this new library ?

@alexandrtovmach I have made a PR to fix this issue over at #3321

**Pull request merged**
