### PR TITLE
Updated type definitions

### PR DESCRIPTION
**Pull request by darkmantle**
The types have changed for react-native causing compiler errors when using TypeScript.

This is a quick change to fix that.

(Note this is a fix of a PR I did a month ago but didn't get around to sorting)

### CODE REVIEW

**Comment by djereg** [comment]
+1
I'm waiting too for this PR.

**Comment by mickaelw** [comment]
@SupriyaKalghatgi When the PR will be good ?
@darkmantle You have some conflicts

**Comment by darkmantle** [comment]
Sigh - was none before!

**Comment by SupriyaKalghatgi** [comment]
@darkmantle Can you pull from master and update this PR?

**Comment by darkmantle** [comment]
@SupriyaKalghatgi Done

**Comment by SupriyaKalghatgi** [comment]
@darkmantle Can you update your PR with the latest update from `master`?

**Comment by darkmantle** [comment]
Done again

**Pull request merged**
