### PR TITLE
Added expanded props to accordion.

### PR DESCRIPTION
**Pull request by akhil-geekyants**

### CODE REVIEW

**Comment by SupriyaKalghatgi** [comment]
@akhil-geekyants Demonstrate this PR with example

**Comment by akhil-geekyants** [comment]
@SupriyaKalghatgi 

expanded

**Comment by jneljneljnel** [comment]
can this be programmatically changed? will the accordion re-render? for example, using dataArray.length -1   as the value for the expanded property does not auto expand the latest

**Comment by jneljneljnel** [comment]
@SupriyaKalghatgi

**Pull request merged**
