### PR TITLE
Content keyboardShouldPersistTaps and keyboardDismissMode typings

### PR DESCRIPTION
**Pull request by bm-software**
Added keyboardShouldPersistTaps and keyboardDismissMode typings on Content component.

### CODE REVIEW

**Comment by bm-software** [comment]
Sorry but I don't understand what is the problem with my PR.

**Comment by SupriyaKalghatgi** [comment]
@bm-software Very difficult to resolve these conflicts
I have pushed it on `development` though, here https://github.com/GeekyAnts/NativeBase/commit/bf3303876f9f7cb9d66f9e9a9c73315e26f655e8

**Comment by bm-software** [comment]
@SupriyaKalghatgi Thank you very much. So these typings will be available with the next release?

**Comment by SupriyaKalghatgi** [comment]
yes

**Pull request closed without merging**
