### PR TITLE
refactor: Fixed linter warnings

### PR DESCRIPTION
**Pull request by alexandrtovmach**
## BEFORE
image

## AFTER
image

This PR solving eslint warnings/errors, that was skipped for a long time. Good practice is to add CI/CD to PRs, to not allow skip linting, and **make it required to pass**. Now it looks like CI/CD in place, but it's not preventing from merge

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
@hanykumar ping

**Comment by alexandrtovmach** [comment]
Amazing, this PR staled, because maintainers didn't pay attention to it =|

**Comment by alexandrtovmach** [comment]
Guys please)

**Comment by shivrajkumar** [comment]
@alexandrtovmach We recently added the stale bot, which marked even the PRs.
We have removed the label which will automatically close the PR and looking into merging this soon

**Comment by alexandrtovmach** [comment]
@shivrajkumar I'm not talking against bot, my question about lack of maintainers activity

**Comment by shivrajkumar** [comment]
@alexandrtovmach I agree we had been inactive on this for some time. But we are actively looking into the issues and PRs now

**Pull request merged**
