### PR TITLE
Fix for issue #1206 (Ripple/Highlight effect on a rounded Button does…

### PR DESCRIPTION
**Pull request by akhil-geekyants**
… not respect border radius)

### CODE REVIEW

**Comment by SupriyaKalghatgi** [comment]
@akhil-geekyants Please check over performance issue here

**Comment by akhil-geekyants** [comment]
@SupriyaKalghatgi Made some change. Can you check this.

**Comment by SupriyaKalghatgi** [comment]
@akhil-geekyants Okay!

**Comment by akhil-geekyants** [comment]
@SupriyaKalghatgi Made some changes. Can you check this.

**Pull request closed without merging**
