### PR TITLE
fix: fab extend theme pseudo prop

### PR DESCRIPTION
**Pull request by Viraj-10**
- Fab component issue. https://github.com/GeekyAnts/NativeBase/issues/5307

### CODE REVIEW

**Comment by Swiftwork** [comment]
@Viraj-10 can you expose/export `useComponentThemeResolver` so developers can use it to extend existing `native-base` components? I for example extend `Button` to create a `ToggleButton` and would like to treat and theme it the same way as other `native-base` components 😄

**Comment by Viraj-10** [comment]
Hi @Swiftwork, Thanks for showing interest but this will be an internal hook for now since API for this hook is subject to change according to the needs.  Also, we are re-thinking this approach.

**Comment by Swiftwork** [comment]
@Viraj-10 Thanks for letting me know. That's unfortunate but understandable.

**Comment by Swiftwork** [comment]
@surajahmed How come this was closed? Are you taking another approach?

**Pull request closed without merging**
