### PR TITLE
Fix build error on v2.4.3

### PR DESCRIPTION
**Pull request by neko-neko**
rubicon-icon-font.ttf and OFL.txt was deleted when 696fba7346c580da117d8355b3941db4d00b7aa7. But `rubicon-icon-font.ttf` is not unnecessary font file.
Re added into `Fonts` dir, please check it.

reference from https://github.com/GeekyAnts/NativeBase/issues/1850

### CODE REVIEW

**Comment by aligfl** [comment]
breaking builds because of this change :(

**Comment by franzejr** [comment]
👍 
2.4.3 is broken because of this missing font.

**Comment by franzejr** [comment]
Thanks @SupriyaKalghatgi ! Now just wait for a new release and use master til there.

**Comment by franzejr** [comment]
Latest version 2.4.3 is broken, yeah.

**Comment by cmmartin** [comment]
@ujwal-setlur Instead of master, you can just use 2.4.2 until it gets published

```
npm install native-base@2.4.2 --save
```

**Comment by ujwal-setlur** [comment]
Yes that's what I did. Actually 2.4.2 works for me.

**Pull request merged**
