### PR TITLE
Add missing useNativeDriver in ToastContainer

### PR DESCRIPTION
**Pull request by hsjoberg**
Hi!
This PR adds a missing `useNativeDriver` inside the `ToastContainer` component.

Cheers

### CODE REVIEW

**Comment by fabiosussetto** [comment]
Can this be released, please? Facing the same issue.

**Comment by summerkiflain** [comment]
Please merge, and publish on npm, thanks

**Comment by copleykj** [comment]
#3278 fixes this issue in multiple components

**Comment by ticoprogrammer** [comment]
Is it already published on npm ? Im using 2.13.14 and im having that issue with FAB.

**Pull request closed without merging**
