### PR TITLE
Fix react native style types refs #27421 #2123

### PR DESCRIPTION
**Pull request by ajmath**
See #2123 for details.  This is an updated version of that PR without any merge conflicts.

### CODE REVIEW

**Comment by ajmath** [comment]
@SupriyaKalghatgi Would you be able to merge this and close out #2123? Without this, the native-base component types are completely broken in newer versions of react-native.

**Comment by smitthakkar1** [comment]
Agree. Thanks @ajmath for the contribution. @SupriyaKalghatgi  can you please look at # 2123?

**Comment by SupriyaKalghatgi** [comment]
@ajmath Can you update your PR with the latest update from `master`?
I merged a couple of PRs yesterday, which seems not present in your PR.

**Comment by ajmath** [comment]
@SupriyaKalghatgi done

**Pull request merged**
