### PR TITLE
Exposed onDateChange method for iOS

### PR DESCRIPTION
**Pull request by akhil-geekyants**

### CODE REVIEW

**Comment by llezcano** [comment]
+1 to android support

**Comment by akhil-geekyants** [comment]
On android there are only two actions 
1. dateSetAction - called when we click the ok button
2. dismissedAction - called when we click the cancel button

On iOS `onDateChange` is called every time the user change the date in the UI.

So adding `onDateChange` for android cannot be supported.

**Comment by llezcano** [comment]
Thanks, I thought both (onDateChange and dateSetAction) were handling the same (a successfully closed datepicker). I was looking for that, maybe is a feature request.

**Comment by ferreirix** [comment]
Sorry if I'm being really dumb but can't we at least call the `props.onDateChange ` when android fires `dateSetAction` ? Because the `dismissedAction` ins't supposed to change any state right?

**Pull request merged**
