### PR TITLE
Fixing warning -> Animated: useNativeDriver was not specified.

### PR DESCRIPTION
**Pull request by blanvam**
Added useNativeDriver to animated.timing call in ToastContainer

### CODE REVIEW

**Comment by favger** [comment]
+++

**Comment by mylesshie** [comment]
+++

**Comment by codler** [comment]
I have [forked](https://github.com/codler/NativeBase) the repo to fix this issue.
```
npm i @codler/native-base
```
You will need to remove old fonts in `Copy Bundle Resources` in Xcode after install

**Comment by hanykumar** [comment]
duplicate #3221

**Comment by summerkiflain** [comment]
Please merge, and publish on npm, thanks

**Comment by copleykj** [comment]
#3278 fixes this issue in multiple components

**Comment by ticoprogrammer** [comment]
Is it already published on npm ? Im using 2.13.14 and im having that issue with FAB.

**Pull request merged**
