### PR TITLE
[Important] Fix Unable to resolve module StaticContainer.react

### PR DESCRIPTION
**Pull request by pierre-H**
Fix https://github.com/facebook/react-native/issues/13545

### CODE REVIEW

**Comment by pierre-H** [comment]
Could you please accept quickly fix pull request because it's very annoying to have to delete every time `.react` ? Thank you !

**Comment by shivrajkumar** [comment]
@pierre-H For RN 43, the path for StaticContainer is StaticContainer.react.
Thus the change in native-base from v2.1.1
If you are using RN < 43, Use native-base v2.1.0

**Comment by pierre-H** [comment]
@shivrajkumar Thank you for your answer !!!
I use RN 0.43.4 and React 15.0.22 with CRNA

**Comment by pierre-H** [comment]
@shivrajkumar and I use NB 2.1.2 and I still have the bug.

**Comment by pierre-H** [comment]
@shivrajkumar you're right : after doing `yarn upgrade react-native` it's working ! Thank you !

**Pull request closed without merging**
