### PR TITLE
Issue #2320: fixing circular dependencies

### PR DESCRIPTION
**Pull request by ranneyd**
There is an index file in the root src file that imports and exports all the components. These two components import various Tab-related components from that index file, but that index file also imports these components themselves. Instead of pulling from that index file I just import them directly.

### CODE REVIEW

**Comment by diegolaciar** [comment]
Hi!

Can someone review & merge this ?  

Changes to files

src/basic/Tabs/DefaultTabBar.js and  src/basic/Tabs/ScrollableTabBar.js

make sense for me.

I have this issue of warnings with circular dependencies to.

@see: https://github.com/GeekyAnts/NativeBase/issues/2320

Thanks

**Comment by tux-tn** [comment]
Hello guys, i think i've implemented the same fix here #2394 more than a month ago but nobody merged it.

**Comment by ranneyd** [comment]
@SupriyaKalghatgi can you review?

**Comment by ranneyd** [comment]
@sanketsahusoft @sankhadeeproy007 @akhil-geekyants @shivrajkumar

**Comment by ranneyd** [comment]
duplicate of #2394

**Pull request closed without merging**
