### PR TITLE
Fixed - Actionsheet of android returns buttonIndex as string instead of number

### PR DESCRIPTION
**Pull request by akhil-geekyants**

### CODE REVIEW

**Comment by akhil-geekyants** [comment]
Fix for issue #1353

**Comment by SupriyaKalghatgi** [comment]
@Empact Yes!, we will add ChangeLog with tags

**Comment by SupriyaKalghatgi** [comment]
Recreated this PR
#1401

**Comment by ceefour** [comment]
Thanks! I just got hit by this. So this will be fixed in 2.3.4 right?

**Comment by SupriyaKalghatgi** [comment]
@ceefour I made a comment in this PR
https://github.com/GeekyAnts/NativeBase/pull/1370#issuecomment-347841546

**Pull request closed without merging**
