### PR TITLE
Fix #2466 adding testID types to all components for detox testing

### LINKED ISSUE #2466: Lack of testID on native base component types result in Property 'testID' does not exist on type 'IntrinsicAttributes  error
## I have gone through these following points
- [X]   Check latest documentation: https://docs.nativebase.io/
- [X]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [X]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [X]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [X]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [X]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version
native-base@2.8.1
react-native@0.55.4
react@16.3.1
xcode 10

### Expected behaviour

testID to be declared on all Native base types

### Actual behaviour

inside index.d.ts there is no declaration of testID on any of native base types
which result in the following error when adding testID on Native base components
>Property 'testID' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Container> & Readonly<{ children?: ReactNode; }> & Readonly<Container>'.

### Steps to reproduce
In Typescript project add `testID` on `Container` component

### PR DESCRIPTION
**Pull request by vnovick**
When Detox is used with Native base, testID prop is missing in types declaration which result in 
the following message:
>Property 'testID' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Container> & Readonly<{ children?: ReactNode; }> & Readonly<Container>'.

Closing issue #2466

### CODE REVIEW

**Comment by SupriyaKalghatgi** [comment]
@vnovick What about people who dont use Detox?

**Comment by vnovick** [comment]
@SupriyaKalghatgi, well testId is provided on all React Native components so it won't hurt add it.

**Comment by SupriyaKalghatgi** [comment]
@vnovick Can you update your PR with the latest update from `master`?

**Comment by EgidioCaprino** [comment]
@vnovick can you please rebase your branch?

**Comment by EgidioCaprino** [comment]
We're not able to test `Tabs` with Detox. Do you know if this would fix our issue?

**Comment by SupriyaKalghatgi** [comment]
Keeping this PR open for this week

**Pull request closed without merging**
